### ISSUE TITLE
a question how do i find the random.as?

### ISSUE THREAD

**Issue by angelaLuna14** [Paranoid-AF/SvenCoop_Plugins#4]
the problem is that it gives me an error and tells me that random.as is missing.
I wanted to put it on a server, because of that error I couldn't, I know I don't have much experience in angel script but I think I followed all the steps to install plugins. As well, I hope it helps me and has a lot of interest in svencoop.

**Comment by Paranoid-AF** [comment]
[Here it is](https://github.com/MrOats/AngelScript_SC_Plugins/blob/master/Random.as). Put it in the same directory as the plugin itself.

Kinda sad that the Sven Co-op forums is down, and the introduction is no longer accessible.

In the mean time, have fun.
