### ISSUE TITLE
KillDrop missing file called Random

### ISSUE THREAD

**Issue by darkfvtvre** [Paranoid-AF/SvenCoop_Plugins#5]
Tried to install the Killdrop plugin on my server and it did not load.  Realized that it needs a file called Random that does not exist.  Do you know where to find that file?

Thanks

**Comment by Paranoid-AF** [comment]
There it is: https://github.com/MrOats/AngelScript_SC_Plugins/blob/master/Random.as
Shout out to MrOats for making such a wonderful thing back in the day.
